site_name: Legacy Modding Wiki
theme: windmill
nav:
  - Home: index.md
copyright: Content is available <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)</a>.
site_description: Wiki about developing mods for legacy versions of Minecraft, such as 1.7.10.
